ARG FEDORA_MAJOR_VERSION
FROM quay.io/fedora-ostree-desktops/silverblue:${FEDORA_MAJOR_VERSION}

ARG FEDORA_MAJOR_VERSION
ARG AKMODS_IMAGE
COPY --from=${AKMODS_IMAGE}:${FEDORA_MAJOR_VERSION} / .
COPY silverblue/setup /usr/bin/silverblue-setup
COPY silverblue/build.sh /tmp/build.sh
RUN /tmp/build.sh
# Cleanup
RUN rm -rf /tmp/* /var/*
# Commit changes
RUN ostree container commit
RUN mkdir -p /var/tmp && chmod -R 1777 /var/tmp