#!/bin/sh
set -ouex pipefail

rpm-ostree upgrade

if [ ! rpm-ostree kargs | grep rd.driver.blacklist=nouveau ]; then
  rpm-ostree kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1
  # This job is done
  reboot
fi

if test -e "$HOME"/.config/firstboot-done; then
  echo "Already ran"
  exit 0
fi

echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done

# Remove flatpaks
# Removing Fedora Flathub Repository
/usr/bin/flatpak remote-delete flathub --force ||:
# Enabling Flathub Repository
/usr/bin/flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
# Removing all preinstalled Flatpaks
/usr/bin/flatpak remove --noninteractive --all --delete-data ||:
# Removing Fedora Flatpak Repository
/usr/bin/flatpak remote-delete fedora --force ||:

echo "# Installing flatpaks"
flatpaks=(
  com.mattjakeman.ExtensionManager
  com.github.tchx84.Flatseal
  com.usebottles.bottles
  io.github.peazip.PeaZip
)
i=0
for pkg in ${flatpaks[@]}; do
  echo "# Installing ${pkg}"
  /usr/bin/flatpak install --noninteractive flathub $pkg
  i=$((i+1))
done

echo "# Config GNOME settings"
# Disable default switching apps shortcuts
for i in $(seq 1 9); do 
    gsettings set org.gnome.shell.keybindings switch-to-application-${i} '[]'; 
done
gsettings set org.freedesktop.ibus.panel.emoji hotkey '[]'

echo "# Config apps"
# Configure shell
usermod --shell $(which zsh) $USER
# Install chezmoi and apply dotfiles
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply TranHHoang -b $HOME/.local/bin
# Disable services
systemctl disable NetworkManager-wait-online.service

# Mark this job as done
mkdir -p "$HOME"/.config
touch "$HOME"/.config/firstboot-done