#!/bin/sh

# First time
if ! test -e "$HOME"/.config/firstboot-done; then
  rpm-ostree kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1
  # This job is done
  mkdir -p "$HOME"/.config
  touch "$HOME"/.config/firstboot-done
  # Schedule the next run
  crontab -l 2>/dev/null; echo -e "@reboot /usr/bin/silverblue-setup\n" | crontab -
  reboot
fi

if test -e "$HOME"/.config/secondboot-done; then
  echo "Already ran"
  exit 0
fi
(
  echo "# Waiting for Internet connection"
  until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
  echo "00"

  echo "# Removing Fedora Flathub Repository"
  /usr/bin/flatpak remote-delete flathub --force ||:
  if [ "$?" != 0 ]; then
      zenity --error \
      --text="Removing Fedora Flathub Repo Failed"
      exit 1
  fi
  echo "3"

  echo "# Enabling Flathub Repository"
  /usr/bin/flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  if [ "$?" != 0 ]; then
      zenity --error \
      --text="Adding Flathub Repo Failed"
      exit 1
  fi
  echo "5"

  echo "# Replacing Fedora Flatpaks with Flathub Ones"
  /usr/bin/flatpak install --noninteractive org.gnome.Platform
  /usr/bin/flatpak install --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
  if [ "$?" != 0 ]; then
      zenity --error \
      --text="Replacing Fedora Flatpaks Failed"
      exit 1
  fi
  echo "20"

  echo "Removing all preinstalled Flatpaks"
  /usr/bin/flatpak remove --noninteractive --all ||:
  if [ "$?" != 0 ]; then
      zenity --error \
      --text="Removing all preinstalled flatpaks failed"
      exit 1
  fi

  echo "# Removing Fedora Flatpak Repository"
  /usr/bin/flatpak remote-delete fedora --force ||:
  if [ "$?" != 0 ]; then
      zenity --error \
      --text="Removing Fedora Flatpak Repo Failed"
      exit 1
  fi
  echo "25"

  echo "# Installing flatpaks"
  flatpaks=$(
    com.mattjakeman.ExtensionManager
    com.github.tchx84.Flatseal
    com.usebottles.bottles
    io.github.peazip.PeaZip
  )
  i=0
  for pkg in ${#flatpaks[@]}; do
      echo "# Installing ${pkg}"
      /usr/bin/flatpak install --user --noninteractive flathub $pkg
      if [ "$?" != 0 ] ; then
              zenity --error \
                  --text="Installing ${pkg} Failed"
              exit 1
      fi
      i=$((i+1))
      # Automatically calculates evenly spaced progess using bc, cuts everything after decimal point.
      echo "${i}/${flatpaks_count} * (95-30) + 30" | bc -l | cut -d "." -f1 
  done
  echo "100"

  echo "Config GNOME settings"
  # Disable default switching apps shortcuts
  for i in $(seq 1 9); do 
      gsettings set org.gnome.shell.keybindings switch-to-application-${i} '[]'; 
  done
  gsettings set org.freedesktop.ibus.panel.emoji hotkey '[]'

  echo "# Cleanup"
  sed -i '/@reboot \/usr\/bin\/silverblue-setup/d' /var/spool/cron/crontabs/root
  rm "$HOME"/.config/firstboot-done
  rm /usr/bin/silverblue-setup
) | zenity --progress --title="Silverblue Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
  zenity --error \
      --text="Firstboot Configuration Error"
fi