ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-38}"
FROM quay.io/fedora-ostree-desktops/silverblue:${FEDORA_MAJOR_VERSION} AS builder

COPY nvidia/build.sh /tmp/build.sh
RUN /tmp/build.sh

FROM scratch
COPY --from=builder /var/cache /var/cache